import Head from 'next/head'
import { gql } from "@apollo/client";
import client from "apollo-client";

import HrText from 'components/Layout/HrText';
import { Row, Col } from 'reactstrap';
import HouseList from 'components/House/HouseList';

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
      {
        houses {
          user {
            id
            name
            family
            email
            avatar
            
          }
          id
          title
          price
          biarea
          larea
          room
          year
          status
          category
          about
          images
        }
      }
    `,
  });

  return {
    props: {
      houses: data.houses,
    },
 };
}

export default function Home(houses) {

  // const houseComp = houses?.houses ? houses?.houses.map((house) => <Col md="3"><HouseThumbnail house={house} /></Col>) : [];

  return (
    <>
      <Head>
        <title>Hemnet - Sweden's largest housing platform</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div style={{textAlign: "center", padding: "20px"}}>
          <Row>
            <Col md="7"  style={{margin: "2px 0", padding: "2px"}}>
               <a href=''>
                <img height={"404px"} style={{width: "100%"}} src={`${process.env.api_domain}${houses?.houses[0]?.images[0]}`} />
              </a>
            </Col>
            <Col md="5" style={{padding: "2px"}} >
              <Row>
                <Col md="12"  style={{margin: "2px 0"}}>
                   <a href=''>
                    <img height={"200px"} style={{width: "100%"}} src={`${process.env.api_domain}${houses?.houses[1]?.images[0]}`} />
                  </a>
                </Col>
                <Col md="12"  style={{margin: "2px 0"}}>
                   <a href=''>
                    <img height={"200px"} style={{width: "100%"}} src={`${process.env.api_domain}${houses?.houses[2]?.images[0]}`} />
                  </a>
                </Col>
              </Row>
            </Col>
          </Row>
          <Row>
            <Col md="4"  style={{margin: "2px 0", padding: "2px"}}>
               <a href=''>
                <img style={{width: "100%"}} src={`${process.env.api_domain}${houses?.houses[3]?.images[0]}`} />
              </a>
            </Col>
            <Col md="4"  style={{margin: "2px 0", padding: "2px"}}>
               <a href=''>
                <img style={{width: "100%"}} src={`${process.env.api_domain}${houses?.houses[4]?.images[0]}`} />
              </a>
            </Col>
            <Col md="4"  style={{margin: "2px 0", padding: "2px"}}>
               <a href=''>
                <img style={{width: "100%"}} src={`${process.env.api_domain}${houses?.houses[5]?.images[0]}`} />
              </a>
            </Col>
          </Row>
        </div>

        <Row style={{padding: "30px 0"}}>
          <h3 style={{width: "100%"}}>
            <HrText text="Top List" />
          </h3>
          {/* <Slider slides={houses?.houses} /> */}
          <HouseList houseList={houses?.houses} />
        </Row>
      </main>
    </>
  )
}
